source "virtualbox-iso" "autogenerated_1" {
  boot_command         = ["<esc><wait>", "<esc><wait>", "<enter><wait>", "/install/vmlinuz<wait>", " initrd=/install/initrd.gz", " auto-install/enable=true", " debconf/priority=critical", " netcfg/get_domain=vm<wait>", " netcfg/get_hostname=vagrant<wait>", " grub-installer/bootdev=/dev/sda<wait>", " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>", " -- <wait>", "<enter><wait>"]
  boot_wait            = "10s"
  disk_size            = 8192
  guest_additions_mode = "disable"
  guest_os_type        = "ubuntu-64"
  #headless             = true
  http_directory       = "http"
  iso_checksum         = "sha256:8c5fc24894394035402f66f3824beb7234b757dd2b5531379cb310cedfdf0996"
  iso_urls             = ["ubuntu-18.04.5-server-amd64.iso", "http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/ubuntu-18.04.5-server-amd64.iso"]
  shutdown_command     = "echo 'vagrant' | sudo -S shutdown -P now"
  ssh_password         = "vagrant"
  ssh_username         = "vagrant"
  ssh_wait_timeout     = "1000s"
  vm_name              = "packer-ubuntu-64-20-04"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["whoami"]
  }
}